(()=>{let user=null,profile=null;const $=id=>document.getElementById(id);const toast=m=>{const e=$("neoToast");if(!e)return;e.textContent=m;e.classList.add("visible");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("visible"),2400)};document.querySelectorAll("[data-toast]").forEach(x=>x.onclick=()=>toast(x.dataset.toast));
const pop=$("accountPopover"),modal=$("authModal");document.querySelectorAll(".js-account").forEach(b=>b.onclick=e=>{e.stopPropagation();if(pop)pop.hidden=!pop.hidden});document.querySelectorAll(".js-search").forEach(b=>b.onclick=()=>{const p=$("searchPanel");if(p){p.hidden=!p.hidden;if(!p.hidden)setTimeout(()=>$("globalSearch")?.focus(),20)}});document.addEventListener("click",e=>{if(pop&&!pop.hidden&&!pop.contains(e.target)&&!e.target.closest(".js-account"))pop.hidden=true});document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(pop)pop.hidden=true;if($("searchPanel"))$("searchPanel").hidden=true;if(modal){modal.classList.remove("visible");setTimeout(()=>modal.hidden=true,180)}}});
function auth(v="login"){if(pop)pop.hidden=true;if(!modal)return;modal.hidden=false;$("loginView").hidden=v!=="login";$("registerView").hidden=v!=="register";$("authMessage").textContent="";setTimeout(()=>modal.classList.add("visible"),10)}function close(){if(!modal)return;modal.classList.remove("visible");setTimeout(()=>modal.hidden=true,180)}
$("openLoginFromMenu")?.addEventListener("click",()=>auth("login"));$("openRegisterFromMenu")?.addEventListener("click",()=>auth("register"));$("showRegister")?.addEventListener("click",()=>auth("register"));$("showLogin")?.addEventListener("click",()=>auth("login"));document.querySelector("[data-close-modal]")?.addEventListener("click",close);modal?.addEventListener("click",e=>{if(e.target===modal)close()});
$("loginForm")?.addEventListener("submit",async e=>{e.preventDefault();$("authMessage").textContent="Signing in…";try{await NeoFirebase.loginNeoID($("loginEmail").value,$("loginPassword").value);close();toast("Welcome back.")}catch(x){$("authMessage").textContent=friendly(x)}});
$("registerForm")?.addEventListener("submit",async e=>{e.preventDefault();$("authMessage").textContent="Creating NeoID…";try{await NeoFirebase.createNeoID($("registerUsername").value,$("registerDisplayName").value,$("registerEmail").value,$("registerPassword").value);close();toast("NeoID created. Verification email sent.")}catch(x){$("authMessage").textContent=friendly(x)}});
$("forgotPasswordButton")?.addEventListener("click",async()=>{const e=$("loginEmail").value.trim();if(!e)return $("authMessage").textContent="Enter your email first.";try{await NeoFirebase.resetNeoPassword(e);$("authMessage").textContent="Password reset email sent."}catch(x){$("authMessage").textContent=friendly(x)}});
$("signOutButton")?.addEventListener("click",async()=>{await NeoFirebase.logoutNeoID();if(pop)pop.hidden=true;toast("Signed out.")});
$("pageResetPassword")?.addEventListener("click",async()=>{if(!user?.email)return toast("Sign in first.");try{await NeoFirebase.resetNeoPassword(user.email);toast("Password reset email sent.")}catch(x){toast(friendly(x))}});
$("pageVerifyEmail")?.addEventListener("click",async()=>{if(!user)return toast("Sign in first.");try{await NeoFirebase.resendVerificationEmail();toast("Verification email sent.")}catch(x){toast(friendly(x))}});
window.addEventListener("neo-auth-state",e=>{user=e.detail?.user||null;profile=e.detail?.profile||null;const signed=!!user,n=profile?.displayName||profile?.username||"NeoID",h=profile?.username?`@${profile.username}`:(user?.email||"Not signed in");if($("signedInMenu"))$("signedInMenu").hidden=!signed;if($("signedOutMenu"))$("signedOutMenu").hidden=signed;if($("accountName"))$("accountName").textContent=signed?n:"NeoID";if($("accountHandle"))$("accountHandle").textContent=h;document.querySelectorAll(".js-account").forEach(b=>b.classList.toggle("is-profile",signed));document.querySelectorAll(".js-account-text").forEach(x=>x.textContent=signed?(n[0]||"N").toUpperCase():"Sign in");if($("menuAvatar"))$("menuAvatar").textContent=signed?(n[0]||"N").toUpperCase():"N";if($("profileName"))$("profileName").textContent=n;if($("profileHandle"))$("profileHandle").textContent=h;if($("profileAvatar"))$("profileAvatar").textContent=(n[0]||"N").toUpperCase();if($("settingsHandle"))$("settingsHandle").textContent=h;if($("settingsEmail"))$("settingsEmail").textContent=user?.email||"—";if($("settingsVerified"))$("settingsVerified").textContent=user?(user.emailVerified?"Verified":"Not verified"):"Signed out"});
function friendly(x){const c=x?.code||"";if(c.includes("invalid-credential"))return"Email or password is incorrect.";if(c.includes("email-already-in-use"))return"That email already has a NeoID.";if(c.includes("too-many-requests"))return"Too many attempts. Try later.";return(x?.message||"Something went wrong.").replace(/^Firebase:\s*/,"").replace(/\s*\(auth\/.*?\)\.?$/,"")}
document.querySelectorAll("img").forEach(i=>i.addEventListener("error",()=>i.style.display="none"));if(!matchMedia("(prefers-reduced-motion: reduce)").matches&&"IntersectionObserver"in window){const io=new IntersectionObserver(es=>es.forEach(({target,isIntersecting})=>{const v=target.querySelector("video");if(v)(isIntersecting?v.play():Promise.resolve(v.pause())).catch?.(()=>{})}),{threshold:.25});document.querySelectorAll("[data-media]").forEach(x=>io.observe(x))}
const cat=$("catalogGrid");if(cat){["Tropical Environment","Modern Materials","Character Base","Coastal Props","Motion Pack","Creator Tools","Studio Lights","Surface Collection"].forEach((n,i)=>cat.insertAdjacentHTML("beforeend",`<article class="catalog-card"><div class="catalog-image c${i%4}"><span>PREVIEW</span></div><div><b>${n}</b><small>@creator · NeoEngine</small></div></article>`))}
$("publishForm")?.addEventListener("submit",async e=>{e.preventDefault();
  const form=e.currentTarget, btn=form.querySelector('button[type="submit"]'), file=$("assetFile")?.files?.[0];
  if(!user)return toast("Sign in with NeoID first.");
  if(!user.emailVerified)return toast("Verify your email before uploading.");
  if(!file)return toast("Select a source file first.");
  const original=btn?.textContent; if(btn){btn.disabled=true;btn.textContent="Uploading…"}
  try{
    const token=await NeoFirebase.getNeoToken();
    const fd=new FormData(); fd.append("file",file);
    const r=await fetch("https://neocorp-api.jorgeemilianolaredovalladares.workers.dev/v1/assets/upload",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:fd});
    const data=await r.json();
    if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);
    toast(`Uploaded: ${data.asset?.id||"asset"}`);
    const status=$("uploadStatus"); if(status)status.innerHTML=`<b>✓ Uploaded to NeoCloud</b><span>${data.asset?.id||""} · ${file.name}</span>`;
  }catch(x){toast(`Upload failed: ${x.message||x}`)}finally{if(btn){btn.disabled=false;btn.textContent=original}}
});
})();